package pojo;

// Generated 17 Jul, 2015 1:34:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlestageId generated by hbm2java
 */
public class ArticlestageId implements java.io.Serializable {

	private String url;
	private String value;

	public ArticlestageId() {
	}

	public ArticlestageId(String url, String value) {
		this.url = url;
		this.value = value;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticlestageId))
			return false;
		ArticlestageId castOther = (ArticlestageId) other;

		return ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
				&& castOther.getUrl() != null && this.getUrl().equals(
				castOther.getUrl())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null && castOther.getValue() != null && this
						.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
