package pojo;

// Generated 17 Jul, 2015 1:39:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Articlestage generated by hbm2java
 */
public class Articlestage implements java.io.Serializable {

	private Integer sno;
	private String url;
	private String value;

	public Articlestage() {
	}

	public Articlestage(String url, String value) {
		this.url = url;
		this.value = value;
	}

	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
