package pojo;

// Generated 20 May, 2015 12:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private Integer articleKey;
	private String aid;
	private String jid;
	private Integer statusId;
	private String site;
	private String title;
	private String correspondingAuthorName;
	private String correspondingAuthorEmail;
	private Date dateArticlePosted;
	private String opturl;
	private Integer expiredForExternalAccess;
	private String stage;
	private Integer datasetStatusId;
	private Integer isDowngradeAccess;
	private Integer offlineStatus;
	private String outxmlstatus;
	private String edited;
	private String purpose;
	private Set userses = new HashSet(0);

	public Article() {
	}

	public Article(String aid, String jid) {
		this.aid = aid;
		this.jid = jid;
	}

	public Article(String aid, String jid, Integer statusId, String site,
			String title, String correspondingAuthorName,
			String correspondingAuthorEmail, Date dateArticlePosted,
			String opturl, Integer expiredForExternalAccess, String stage,
			Integer datasetStatusId, Integer isDowngradeAccess,
			Integer offlineStatus, String outxmlstatus, String edited,
			String purpose, Set userses) {
		this.aid = aid;
		this.jid = jid;
		this.statusId = statusId;
		this.site = site;
		this.title = title;
		this.correspondingAuthorName = correspondingAuthorName;
		this.correspondingAuthorEmail = correspondingAuthorEmail;
		this.dateArticlePosted = dateArticlePosted;
		this.opturl = opturl;
		this.expiredForExternalAccess = expiredForExternalAccess;
		this.stage = stage;
		this.datasetStatusId = datasetStatusId;
		this.isDowngradeAccess = isDowngradeAccess;
		this.offlineStatus = offlineStatus;
		this.outxmlstatus = outxmlstatus;
		this.edited = edited;
		this.purpose = purpose;
		this.userses = userses;
	}

	public Integer getArticleKey() {
		return this.articleKey;
	}

	public void setArticleKey(Integer articleKey) {
		this.articleKey = articleKey;
	}

	public String getAid() {
		return this.aid;
	}

	public void setAid(String aid) {
		this.aid = aid;
	}

	public String getJid() {
		return this.jid;
	}

	public void setJid(String jid) {
		this.jid = jid;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCorrespondingAuthorName() {
		return this.correspondingAuthorName;
	}

	public void setCorrespondingAuthorName(String correspondingAuthorName) {
		this.correspondingAuthorName = correspondingAuthorName;
	}

	public String getCorrespondingAuthorEmail() {
		return this.correspondingAuthorEmail;
	}

	public void setCorrespondingAuthorEmail(String correspondingAuthorEmail) {
		this.correspondingAuthorEmail = correspondingAuthorEmail;
	}

	public Date getDateArticlePosted() {
		return this.dateArticlePosted;
	}

	public void setDateArticlePosted(Date dateArticlePosted) {
		this.dateArticlePosted = dateArticlePosted;
	}

	public String getOpturl() {
		return this.opturl;
	}

	public void setOpturl(String opturl) {
		this.opturl = opturl;
	}

	public Integer getExpiredForExternalAccess() {
		return this.expiredForExternalAccess;
	}

	public void setExpiredForExternalAccess(Integer expiredForExternalAccess) {
		this.expiredForExternalAccess = expiredForExternalAccess;
	}

	public String getStage() {
		return this.stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	public Integer getDatasetStatusId() {
		return this.datasetStatusId;
	}

	public void setDatasetStatusId(Integer datasetStatusId) {
		this.datasetStatusId = datasetStatusId;
	}

	public Integer getIsDowngradeAccess() {
		return this.isDowngradeAccess;
	}

	public void setIsDowngradeAccess(Integer isDowngradeAccess) {
		this.isDowngradeAccess = isDowngradeAccess;
	}

	public Integer getOfflineStatus() {
		return this.offlineStatus;
	}

	public void setOfflineStatus(Integer offlineStatus) {
		this.offlineStatus = offlineStatus;
	}

	public String getOutxmlstatus() {
		return this.outxmlstatus;
	}

	public void setOutxmlstatus(String outxmlstatus) {
		this.outxmlstatus = outxmlstatus;
	}

	public String getEdited() {
		return this.edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
