package pojo;

// Generated 20 May, 2015 12:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Checkpoint generated by hbm2java
 */
public class Checkpoint implements java.io.Serializable {

	private Integer sno;
	private String journalId;
	private String articleId;
	private String dataset;
	private String metaXmlname;
	private String zipfileName;
	private int status;

	public Checkpoint() {
	}

	public Checkpoint(String metaXmlname, int status) {
		this.metaXmlname = metaXmlname;
		this.status = status;
	}

	public Checkpoint(String journalId, String articleId, String dataset,
			String metaXmlname, String zipfileName, int status) {
		this.journalId = journalId;
		this.articleId = articleId;
		this.dataset = dataset;
		this.metaXmlname = metaXmlname;
		this.zipfileName = zipfileName;
		this.status = status;
	}

	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	public String getJournalId() {
		return this.journalId;
	}

	public void setJournalId(String journalId) {
		this.journalId = journalId;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	public String getMetaXmlname() {
		return this.metaXmlname;
	}

	public void setMetaXmlname(String metaXmlname) {
		this.metaXmlname = metaXmlname;
	}

	public String getZipfileName() {
		return this.zipfileName;
	}

	public void setZipfileName(String zipfileName) {
		this.zipfileName = zipfileName;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
