package pojo;

// Generated 20 May, 2015 12:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Datasethistory generated by hbm2java
 */
public class Datasethistory implements java.io.Serializable {

	private Integer sno;
	private Datasetstatus datasetstatus;
	private String datasetid;
	private String message;
	private String stage;
	private Date processTime;

	public Datasethistory() {
	}

	public Datasethistory(Datasetstatus datasetstatus, String datasetid,
			String stage) {
		this.datasetstatus = datasetstatus;
		this.datasetid = datasetid;
		this.stage = stage;
	}

	public Datasethistory(Datasetstatus datasetstatus, String datasetid,
			String message, String stage, Date processTime) {
		this.datasetstatus = datasetstatus;
		this.datasetid = datasetid;
		this.message = message;
		this.stage = stage;
		this.processTime = processTime;
	}

	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	public Datasetstatus getDatasetstatus() {
		return this.datasetstatus;
	}

	public void setDatasetstatus(Datasetstatus datasetstatus) {
		this.datasetstatus = datasetstatus;
	}

	public String getDatasetid() {
		return this.datasetid;
	}

	public void setDatasetid(String datasetid) {
		this.datasetid = datasetid;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getStage() {
		return this.stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	public Date getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(Date processTime) {
		this.processTime = processTime;
	}

}
