package pojo;

// Generated 2 Jun, 2015 4:36:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * Journal generated by hbm2java
 */
public class Journal implements java.io.Serializable {

	private Integer jkey;
	private String jid;
	private String jexpansion;
	private String mailId;

	public Journal() {
	}

	public Journal(String jid) {
		this.jid = jid;
	}

	public Journal(String jid, String jexpansion, String mailId) {
		this.jid = jid;
		this.jexpansion = jexpansion;
		this.mailId = mailId;
	}

	public Integer getJkey() {
		return this.jkey;
	}

	public void setJkey(Integer jkey) {
		this.jkey = jkey;
	}

	public String getJid() {
		return this.jid;
	}

	public void setJid(String jid) {
		this.jid = jid;
	}

	public String getJexpansion() {
		return this.jexpansion;
	}

	public void setJexpansion(String jexpansion) {
		this.jexpansion = jexpansion;
	}

	public String getMailId() {
		return this.mailId;
	}

	public void setMailId(String mailId) {
		this.mailId = mailId;
	}

}
