package pojo;

// Generated 20 May, 2015 12:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer sno;
	private Article article;
	private String customer;
	private String jid;
	private String aid;
	private String password;
	private String filepath;
	private String pdfpath;
	private String size;
	private Date opened;
	private Date modified;
	private String status;
	private String token;
	private String uname;
	private Integer signIn;
	private String ip;
	private Integer checkSaved;

	public Users() {
	}

	public Users(Article article, String jid, String aid, String filepath,
			String token) {
		this.article = article;
		this.jid = jid;
		this.aid = aid;
		this.filepath = filepath;
		this.token = token;
	}

	public Users(Article article, String customer, String jid, String aid,
			String password, String filepath, String pdfpath, String size,
			Date opened, Date modified, String status, String token,
			String uname, Integer signIn, String ip, Integer checkSaved) {
		this.article = article;
		this.customer = customer;
		this.jid = jid;
		this.aid = aid;
		this.password = password;
		this.filepath = filepath;
		this.pdfpath = pdfpath;
		this.size = size;
		this.opened = opened;
		this.modified = modified;
		this.status = status;
		this.token = token;
		this.uname = uname;
		this.signIn = signIn;
		this.ip = ip;
		this.checkSaved = checkSaved;
	}

	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	public String getJid() {
		return this.jid;
	}

	public void setJid(String jid) {
		this.jid = jid;
	}

	public String getAid() {
		return this.aid;
	}

	public void setAid(String aid) {
		this.aid = aid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getPdfpath() {
		return this.pdfpath;
	}

	public void setPdfpath(String pdfpath) {
		this.pdfpath = pdfpath;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Date getOpened() {
		return this.opened;
	}

	public void setOpened(Date opened) {
		this.opened = opened;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public Integer getSignIn() {
		return this.signIn;
	}

	public void setSignIn(Integer signIn) {
		this.signIn = signIn;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getCheckSaved() {
		return this.checkSaved;
	}

	public void setCheckSaved(Integer checkSaved) {
		this.checkSaved = checkSaved;
	}

}
